### ISSUE TITLE
[Feature request] Repeating the header in console table widget

### ISSUE THREAD

**Issue by DBX12** [yiisoft/yii-console#10]
It would be nice if the column headers would be repeated every `x` data rows, so you don't loose track which column is which. `x` could be linked to the window height.

I think about something like this:

```
+---------------+----------+-----------+------------+------------+
| name          | can read | can write | can update | can delete |
+---------------+----------+-----------+------------+------------+
| john.doe      |    1     |     0     |    0       |    0       |
+---------------+----------+-----------+------------+------------+
<about x rows>
+---------------+----------+-----------+------------+------------+
| name          | can read | can write | can update | can delete |
+---------------+----------+-----------+------------+------------+
| jane.doe      |    1     |     1     |    1       |    1       |
+---------------+----------+-----------+------------+------------+
```

**Comment by DBX12** [comment]
Sad to see this closed, care to elaborate why this got closed?

**Comment by samdark** [comment]
Because enhancements are no longer accepted into Yii 2.0: https://www.yiiframework.com/news/156/yii-2-1-and-yii-2-0-feature-freeze

**Comment by samdark** [comment]
Back then it was Yii 2.1, now it's Yii 3 that is in heavy development.

**Comment by DBX12** [comment]
Alright, thank you for the explanation.
Is this feature already in Yii 3 or should I reopen the feature request there?

**Comment by samdark** [comment]
I think it's no there. https://github.com/yiisoft/yii-console

**Comment by DBX12** [comment]
I'm not sure I can follow. The yii-core repo contained everything for yii3 but it was split and archived. I did not find a yii3-console repo, but this one is tagged `yii3`. Can you point me to the right repo or am I in the right repo here?

**Comment by samdark** [comment]
You are in the right repo.

**Comment by DBX12** [comment]
So just to get this right (I don't want to be annoying, just want to understand it):
- this is the repo for the console functionalities of yii3
- a feature freeze was issued for yii2
- I should move the issue to the repo for yii3 console functionalities
- The issue is here, yet the issue is in the wrong repo?

**Comment by samdark** [comment]
It is in the right repo. Console is now based on different codebase where there's no such issue.
