### ISSUE TITLE
XDebug doesn't work

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-console#118]
### What steps will reproduce the problem?
1. Enable XDebug profiling
2. Set breakpoint
3. Run `XDEBUG_TRIGGER=yes php -dxdebug.mode=debug yii serve` in console
4. Run code where you set breakpoint

### What is the expected result?
IDE catches the running at needed line

### What do you get instead?
IDE doesn't catch nothing

## Supposed solution
The problem is located on https://github.com/yiisoft/yii-console/blob/master/src/Command/Serve.php#L97
That command should consider arguments what was passed to original process.

**Comment by samdark** [comment]
Seems to be resolved now. Verified by @devanych.
