### ISSUE TITLE
add application-base init commands

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-console#12]
### What steps will reproduce the problem?

Install a project template, people complaining about too complicated setup.

### What is the expected result?

Example commands

```
$ yii init
Querying application bases...
[1] yii-base-web
[2] yii-base-api
[3] yii-base-cli
Which one(s) do you want to install?
```

### What do you get instead?

Copy and paste command from docs.

**Comment by samdark** [comment]
I'm against having init command.

**Comment by schmunk42** [comment]
I am against having a web-application installed by default, primarily based on the discussion in https://github.com/yiisoft/yii-base-api/issues/1 and the comments from @roslov and @rob006 

An init command could be attached to the **post-create-project** hook of composer and detect if npm and or yarn is available. If so I'd suggest to offer this as the primary asset-management with foxy, if not the only option is to use asset-packagist.

**Comment by samdark** [comment]
What if web application won't install any external assets?

**Comment by schmunk42** [comment]
That would simplify things a lot!

**Comment by samdark** [comment]
Let's close this one then. If it will be still too complicated, we'll add some commands.
