### ISSUE TITLE
./yii serve not works in windows PHP 8.0, PHP 8.1.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-console#140]
https://github.com/yii-extension/simple-app/actions/runs/1452155844

1) ErrorCest: See error page.
 Test  tests\acceptance\ErrorCest.php:testErrorPage

 [GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to localhost port 8080: Connection refused (see 
https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:8080/about  

Scenario Steps:

 2. $I->amOnPage("/about") at tests\acceptance\ErrorCest.php:14
 1. // I am going to go to the error page

#1  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
#2  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:158
#3  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:110
#4  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php:47
#5  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php:35
#6  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Middleware.php:37
#7  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php:55
#8  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Middleware.php:63
#9  D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\HandlerStack.php:75
#10 D:\a\simple-app\simple-app\vendor\guzzlehttp\guzzle\src\Client.php:331

With the integrated PHP server curl does not fail.

**Comment by samdark** [comment]
Can you try 127.0.0.1 instead of localhost?

**Comment by samdark** [comment]
Here: https://github.com/yii-extension/simple-app/blob/master/tests/acceptance.suite.yml#L11

**Comment by samdark** [comment]
With 127.0.0.1 it definitely works and that is our new default value.
