### ISSUE TITLE
Typo in config file

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii-console#15]
https://github.com/yiisoft/yii-console/blob/a879c21bb83faf744e1323585a52666e6e019635/config/console.php#L6

Seems as typo and possible meaning 'yii\console\controllers' ? There are no class '\yii\console\controllers' - its a directory

**Comment by hiqsol** [comment]
No, it's not typo, it is on purpose.
I think it is a convenient way to write namespaces uniformly with classes.

**Comment by Insolita** [comment]
Ok, but at first time is confused :smile:

**Comment by SilverFire** [comment]
Agreed, it's a good practice as for me
