### ISSUE TITLE
Incorrect controller path detection

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii-console#16]
### What steps will reproduce the problem?
1, Folder structure

 ```
- App
   -- Commands
       --- HelloController.php
- config
    -- common.php
    -- console.php
    -- params.php
...
- vendor
- composer.json
```

2, composer.json

```
 { 
...
 "extra": {
        "branch-alias": {
            "dev-master": "3.0.x-dev"
        },
        "config-plugin": {
            "params": ["config/params.php"],
            "common": ["config/common.php"],
            "console": [
                "$common",
                "config/console.php"
            ]
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "App",
            "Lib\\": "Lib"
        }
    },
}
...
```
3.  config parts

console.php

```php
return [
    'app' => [
        'controllerNamespace' => 'App\Commands', // (Also trying with App\Commands::class)
    ],
];
``` 
common.php
```php
return [
   'app' => [
        'basePath' => dirname(__DIR__) . '/App',
    ],
   ....
]
```

When i run 
```/vendor/bin/yii hello/index ```   - all correct, it works 
   
When i run 
```/vendor/bin/yii help ```   - gotcha error 

**Error: Invalid path alias: @/App/Commands**

Also if i add in my HelloController@actionIndex  print app->controllerPath, error also reproduced

```
public function actionIndex(): int
    {
        $this->stdout('Hello, Yii3'.PHP_EOL, Console::FG_PURPLE); //It`s normal
        // With this line  error reproduced
        $this->stdout($this->app->controllerPath.PHP_EOL, Console::FG_PURPLE);

        return ExitCode::OK;
    }
```

### What is the expected result?
alias should be '@App/Commands'
### What do you get instead?
Error: Invalid path alias: @/App/Commands

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0.? -latest dev-master
| PHP version      | 7.3
| Operating system | ArchLinux

**Comment by Insolita** [comment]
As a way, it can be fixed in 

 https://github.com/yiisoft/yii-core/blob/e7dd2905e25976a3109a2d4b831694968f63cea6/src/base/Module.php#L271

by adding check for leading slash in controllerNamespace

```php
public function getControllerPath()
    {
        $path = ltrim(str_replace('\\', '/', $this->controllerNamespace),'/');
        return $this->app->getAlias('@' .$path);
    }
```

**Comment by machour** [comment]
Let's track this one in https://github.com/yiisoft/yii-core/issues/113
