### ISSUE TITLE
Shortcuts do not work

### ISSUE THREAD

**Issue by BoShurik** [yiisoft/yii-console#172]
With `:` separator you can run command `doctrine:migrations:diff` by `d:mi:di`. 
This do not work for `/` separator. E.g. `debug/reset` can't be executed by `d/r`

**Comment by samdark** [comment]
Tried solving it but it doesn't seem to be an easy one. `:` is hardcoded in many places in the symfony console.

**Comment by samdark** [comment]
After inspecting the code, internal discussions and votring, we've decided to follow default Symfony console conventions i.e. using `:` as command separator.
