### ISSUE TITLE
Error Help controllers actions list

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii-console#20]
This is (I think) an error also in Yii2 console.

Help controller actions list is wrong because \yii\console\Application has wrong controllerNamespace that returns wrong list here:

https://github.com/yiisoft/yii-console/blob/e6252c2cd4e3c98c510404edc763c26dcf31e311/src/controllers/HelpController.php#L246

![schermata 2019-01-13 alle 00 11 18](https://user-images.githubusercontent.com/4108673/51079503-6da04100-16c8-11e9-8367-bf29e18a602a.png)

This is the test match list:

https://github.com/yiisoft/yii-console/blob/e6252c2cd4e3c98c510404edc763c26dcf31e311/tests/unit/controllers/HelpControllerTest.php#L66-L75

but if we look at controllers folder list : 

![schermata 2019-01-13 alle 00 18 22](https://user-images.githubusercontent.com/4108673/51079518-c4a61600-16c8-11e9-8c20-db9743f6b581.png)

**Comment by machour** [comment]
@FabrizioCaldarelli is this fixed by #21 ? (I'm not understanding the issue you're reporting)

**Comment by FabrizioCaldarelli** [comment]
Yes, but I have changed tests. 

I think that there is an error in path resolution and old (Yii2) tests are wrong, in my opinion.
