### ISSUE TITLE
Missing container dependency

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-console#44]
`bin/yii` file is [using our own DI container](https://github.com/yiisoft/yii-console/blob/master/bin/yii#L5). I guess we shouldn't require it, but we should not use it directly. Any suggestions?

**Comment by viktorprogger** [comment]
Do you mean I should make my own entry point if I don't want to use this particular package?

**Comment by samdark** [comment]
What would you propose instead?

We have no yiisoft/di required btw. so out of the box w/o Yii app in place `./vendor/bin/yii` just errors...
