### ISSUE TITLE
Find a way not to instantiate every command when getting a command list

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-console#46]
Currently Symfony console instantiates every command when making a list. That means all the dependencies are instantiated as well. Some of these such as Cycle, are making SQL queries.

Overall, instantiating every command isn't needed since what we need is some meta-data that seems to be OK as static.

TODO:

- [x] Support static $defaultDescription property. https://github.com/yiisoft/yii-console/pull/124
- [ ] Document it.
- [ ] Apply to yii-cycle.
- [ ] Apply to debug.
- [ ] Apply to migrations.
- [ ] Apply to router/list (demo).
- [ ] Apply to user/create (demo).

**Comment by armpogart** [comment]
@samdark Issue on symfony repo for reference: https://github.com/symfony/symfony/issues/33804

**Comment by samdark** [comment]
@roxblnfk solved the issue in concrete command. Likely with https://github.com/Ocramius/ProxyManager it could be solved in general.

**Comment by samdark** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve console application](https://trello.com/c/7CjdStTQ/32-improve-console-application)

**Comment by mapeveri** [comment]
I would like take this issue, but I need more information. I am new, but this issue is very interesting for me.
Thanks!

**Comment by samdark** [comment]
What information do you need? Feel free to ask questions.

**Comment by mapeveri** [comment]
@samdark, I saw the trello board and it says this: "Remain as it is, but add caching to help. This is good, but cache should be recreated each time commands are changed. It is expensive.
Write our own implementation with the base architecture of symfony/console and the best from yii2 console controller. Write our own yii2-like implementation."

I understand the problem, that to list commands of the application, this create a new instance for all dependencies. But the solution to implement is not clear to me. I understand that I have to do these two steps:

1. Add cache
2. Write our own implementation with the base architecture of symfony/console and the best from yii2 console controller. Write our own yii2-like implementation

The first step any comments to add?. Related to second step, here I need understand this point :)

**Comment by samdark** [comment]
1. No, it is what it sounds like. Adding cache.
2. It is about exploring another way to achieve it. I don't see any except some form of caching for now.

**Comment by mapeveri** [comment]
@samdark for the cache I add  the component cache to dependencies?. And the caching I would have to do in this file: https://github.com/yiisoft/yii-console/blob/master/bin/yii when is creating the application right?, Further you say this " but cache should be recreated each time commands are changed" where is this?. 

Many thanks!

**Comment by roxblnfk** [comment]
I think you have chosen not the easiest problem to solve.
Also we do not yet have a clear idea of ​​the correct solution to this problem.

**Comment by samdark** [comment]
No. Add PSR cache interface instead.

**Comment by BoShurik** [comment]
[There is](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Command/Command.php#L255-L258) `setCode` method which executed if set.

You can introduce own `AbstractCommand extends Command`
```php
public function __construct(callable $executor)
{
    parent::__construct(null);

    $this->setCode($executor);
}
```

`$executor` can be wrapped with mentioned `ProxyManager`

**Comment by viktorprogger** [comment]
There was a decision made in a private conversation.
There should be an independent implementation of console application. Some parts of `symfony/console` should be used, though:
- input
- output
- output formatter
- progress bar helper
- question helper

We can't use them directly, so we should port them here and make some adoption (everything should be configurable with ease through DI container, no instantiation inside commands and applications as it made in `symfony/console`).

**Comment by BoShurik** [comment]
FYI: symfony/symfony#33804 is resolved via symfony/symfony#39851

**Comment by samdark** [comment]
Since that's already solved in the upstream package, we need to check if we use the static property.

**Comment by vjik** [comment]
> Since that's already solved in the upstream package, we need to check if we use the static property.

Seems this work only with symfony DI-container: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php

**Comment by BoShurik** [comment]
It's a compiler pass for defining commands with tags. Lazy commands should work out of the box

**Comment by vjik** [comment]
> It's a compiler pass for defining commands with tags. Lazy commands should work out of the box

I'm try add static `defaultName` and `defaultDescription`  to command and lazy load don't work. Judging by the code all commands getting from command loader when output the list of commands.

**Comment by BoShurik** [comment]
Yes, looks like need to adjust [CommandLoader](https://github.com/yiisoft/yii-console/blob/master/src/CommandLoader.php#L45) to return `LazyCommand` instead of `Command` instance
