### ISSUE TITLE
symfony/console support?

### ISSUE THREAD

**Issue by zacksleo** [yiisoft/yii-console#9]
### Feature request

symfony/console is a great component which many frameworks used. So can we support it , or how can I integrate with it seamless? 

https://symfony.com/doc/current/components/console.html

**Comment by samdark** [comment]
Symfony console is the whole console framework so it makes no sense to integrate it. Which specific features of Symfony console are you missing in Yii?

**Comment by zacksleo** [comment]
Nothing missing. Many frameworks I am using at the same time, including developing cli library, just want same api to reduce my work.  It is just a proposal, closing now.
